version: 1.0.{build}
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore EntityFramework.AsyncEx.sln
build:
  project: EntityFramework.AsyncEx.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies: '**\Tests.*.dll'
deploy:
- provider: NuGet
  api_key:
    secure: aG/3Ue+5ESWh+XU47NRTQHmCH1RrXlM85xDqy0pIatVXGqtG1vTTZ61UbjTSs+Y5
  skip_symbols: true